add_rules("mode.debug", "mode.release")

add_requires("glfw", "glad", "assimp")
target("LearnOpenGL")
set_kind("binary")
set_languages("c++17")
add_files("src/*.cpp")
add_packages("glfw", "glad", "assimp")
on_run(function(target)
	os.cd("F:\\GraphicsLearningHub\\LearnOpenGL\\")
	os.execv(target:targetfile(), argv)
end)
